repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0  # check for latest stable version
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
