name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Deps
        run: |
          cd backend
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          cd backend
          pytest

      - name: Build Backend
        run: |
          docker-compose build backend

      - name: Run Backend Tests
        run: |
          docker-compose run backend pytest
